function exp_trial_save( epar, tn )
%EXP_SAVE_TRIAL Summary of this function goes here
%   Detailed explanation goes here

fid = fopen(epar.log_file,'a');
fprintf(fid,'%d\t%d\t%d\t%d\t %.2f\t%d\t%d\t%.2f\t%.2f\t%.2f\t%.2f\t%.2f\t%.2f\t%.2f\t%.2f\t %.2f\n',...
    epar.experiment,...
    epar.subject,...
    epar.block,...
    tn,...
    epar.gabor.sf,...
    epar.gabor.contrast(1),...
    epar.gabor.sd,...
    epar.trial.motion_dir(tn),...
    epar.trial.speed(tn),...
    epar.step,...
    epar.step_frame,...
    epar.end_frame,...
    epar.gabor.xs,...
    epar.gabor.ys,...
    epar.gabor.xm,...
    epar.gabor.ym);
fclose(fid);